# Generated by Django 3.2 on 2021-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('published_year', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('book_img', models.ImageField(blank=True, null=True, upload_to='bookapp/bookImg/')),
            ],
        ),
    ]
