# Generated by Django 3.2 on 2021-04-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
