# Generated by Django 3.2 on 2021-04-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_book_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_detail',
            new_name='book_category',
        ),
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
