# Generated by Django 3.2 on 2021-04-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20210420_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_adultCustomer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_childCustomer',
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, verbose_name='telephone'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=2, verbose_name='user_type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
