# Generated by Django 3.2 on 2021-04-20 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20210420_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dob'),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='join_date'),
        ),
    ]
