# Generated by Django 3.2 on 2021-04-20 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20210420_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.date(2021, 4, 20)),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Design for whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
