# Generated by Django 3.2 on 2021-04-20 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20210420_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 10, 18, 46, 863383), verbose_name='dob'),
        ),
    ]
