# Generated by Django 3.2 on 2021-04-20 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=False, help_text='Design fr whether the user can view all books or not.', verbose_name='is_adult'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 11, 11, 44, 137937), verbose_name='dob'),
        ),
    ]
