# Generated by Django 3.2 on 2021-04-20 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_auto_20210420_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 12, 33, 46, 300525), verbose_name='dob'),
        ),
    ]
