# Generated by Django 3.2 on 2021-04-22 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_alter_book_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='storeapp/bookImg/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.date(2021, 4, 22)),
        ),
    ]
