# Generated by Django 3.2 on 2021-04-23 23:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0018_auto_20210422_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.date(2021, 4, 23)),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 23, 36, 39, 558647, tzinfo=utc), verbose_name='dob'),
        ),
    ]
