# Generated by Django 3.2 on 2021-04-23 23:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0019_auto_20210423_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 23, 38, 32, 246008, tzinfo=utc), verbose_name='dob'),
        ),
    ]
