# Generated by Django 3.2 on 2021-04-24 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.date(2021, 4, 24)),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.date(2021, 4, 24)),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.date(2021, 4, 24)),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=2),
        ),
    ]
