# Generated by Django 3.2 on 2021-04-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0022_auto_20210425_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_img',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
